### ISSUE TITLE
Can we toggle full zoom mode instead of having to hold down a button?

### ISSUE THREAD

**Issue by SuperHendrix** [superlime/hoverzoomgold#2]
That's really my only gripe with the extension, being able to have the popup centred so we can move the mouse around would be cool as well (upon activating the full zoom mode) but just a toggle would be cool, thanks.

**Comment by superlime** [comment]
Heya!  Sorry I completely missed your issue until just now!  Do you mean you'd want to mouse over the image, press a key, and then have the popup stay in place until you dismissed it (pressing the key again, maybe)?

**Comment by superlime** [comment]
Reopen if you're still interested in this, you're the only one who has requested it and just want to make sure you still care before I work on it.  :)
